openapi: 3.0.0

info:
  title: Carts API
  description: API for managing shopping cart contents
  version: 1.0.0
  contact:
    name: Shuhei Kawamura
    email: shuhei.kawamura@konghq.com

servers:
  - url: http://localhost:8000
    description: Local development server

tags:
  - name: gorilla-ec
    description: Endpoints related to the Gorilla E-Commerce application
  - name: cart
    description: Endpoints related to the shopping cart

paths:
  /cart:
    get:
      operationId: getCartContents
      summary: Get cart contents
      description: Retrieve the current contents of the shopping cart
      tags:
        - gorilla-ec
        - cart
      responses:
        "200":
          description: A list of items in the cart
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/cartItem"
    post:
      operationId: addItemToCart
      summary: Add an item to the cart
      description: Add a new item to the shopping cart
      tags:
        - gorilla-ec
        - cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/cartItem"
      responses:
        "201":
          description: Item added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/cartItem"
    delete:
      operationId: clearCart
      summary: Clear the cart
      description: Remove all items from the shopping cart
      tags:
        - gorilla-ec
        - cart
      responses:
        "204":
          description: Cart cleared
  /cart/{id}:
    delete:
      operationId: removeItemFromCart
      summary: Remove an item from the cart
      description: Remove a specific item from the shopping cart
      tags:
        - gorilla-ec
        - cart
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Item removed

components:
  schemas:
    cartItem:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
        imageUrl:
          type: string
