openapi: 3.0.0

info:
  title: Catalogue API
  description: API for managing product catalog
  version: 1.0.0
  contact:
    name: Shuhei Kawamura
    email: shuhei.kawamura@konghq.com

servers:
  - url: http://localhost:8000
    description: Local development server

tags:
  - name: gorilla-ec
    description: Endpoints related to the Gorilla E-Commerce application
  - name: catalogue
    description: Endpoints related to the product catalogue

paths:
  /catalogue:
    get:
      operationId: getAllProducts
      summary: Get all products
      description: Retrieve a list of all products in the catalogue
      tags:
        - gorilla-ec
        - catalogue
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/product'

components:
  schemas:
    product:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
        imageUrl:
          type: string
