openapi: 3.0.0

info:
  title: Orders API
  description: API for managing customer orders
  version: 1.0.0
  contact:
    name: Shuhei Kawamura
    email: shuhei.kawamura@konghq.com

servers:
  - url: http://localhost:8000
    description: Local development server

tags:
  - name: gorilla-ec
    description: Endpoints related to the Gorilla E-Commerce application
  - name: orders
    description: Endpoints related to customer orders

paths:
  /orders:
    get:
      operationId: getOrders
      summary: Get all orders
      description: Retrieve a list of all customer orders
      tags:
        - gorilla-ec
        - orders
      responses:
        '200':
          description: A list of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/order'
    post:
      operationId: createOrder
      summary: Create a new order
      description: Create a new customer order
      tags:
        - gorilla-ec
        - orders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/order'
      responses:
        '201':
          description: Order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
        '500':
          description: Internal Server Error (50% chance of failure)

components:
  schemas:
    order:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/cartItem'
    cartItem:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
        imageUrl:
          type: string
